project_id = "kjvdmadoqibvhkfcuzxh"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.subscription-check]
verify_jwt = true

[functions.user-info]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true
